# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies with ignore-scripts to skip building native addons if any
RUN npm install --ignore-scripts

# Copy the rest of the code
COPY . .

# Build the project
RUN npm run build

# Expose port if necessary (MCP may not listen on a specific port, using stdio typically)

# Start the server
CMD [ "node", "dist/index.js" ]
